version: '3.8'

services:
  # Laravel Backend & Vue Frontend
  laravel-app:
    image: php:8.4-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db

  # MySQL Database
  mysql-db:
    image: mysql:8.0.46
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 